# Generated by Django 5.0.6 on 2024-05-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('O', 'Otro')], max_length=1)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivos_pdf', models.FileField(upload_to='fichas_medicas/')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='app.mascota')),
            ],
        ),
    ]
